export const RESET_STATE = 'CHECKOUT_RESET_STATE';
export const CURRENT_ITEM = 'CHECKOUT_CURRENT_ITEM';

export const REQUEST_LOADING = 'CHECKOUT_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'CHECKOUT_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'CHECKOUT_REQUEST_FAILED';

export const CURRENT_ACTION = 'CHECKOUT_CURRENT_ACTION';
export const RESET_ACTION = 'CHECKOUT_RESET_ACTION';
export const ADD_ITEM = 'CHECKOUT_ADD_ITEM';
export const GET_ITEM = 'CHECKOUT_GET_ITEM';
